models/UnitKerjaProdi.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "unit_kerja_prodi".
 *
 * @property int $id
 * @property int|null $unit_kerja_id
 * @property int|null $prodi_id
 *
 * @property Prodi $prodi
 * @property UnitKerja $unitKerja
 */
class UnitKerjaProdi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'unit_kerja_prodi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['unit_kerja_id', 'prodi_id'], 'integer'],
            [['prodi_id'], 'exist', 'skipOnError' => true, 'targetClass' => Prodi::class, 'targetAttribute' => ['prodi_id' => 'id']],
            [['unit_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => UnitKerja::class, 'targetAttribute' => ['unit_kerja_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unit_kerja_id' => 'Unit Kerja ID',
            'prodi_id' => 'Prodi ID',
        ];
    }

    /**
     * Gets query for [[Prodi]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProdi()
    {
        return $this->hasOne(Prodi::class, ['id' => 'prodi_id']);
    }

    /**
     * Gets query for [[UnitKerja]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUnitKerja()
    {
        return $this->hasOne(UnitKerja::class, ['id' => 'unit_kerja_id']);
    }
}

controllers/UnitKerjaProdiController.php
<?php

namespace app\controllers;

use Yii;
use app\models\UnitKerjaProdi;
use app\models\UnitKerjaProdiSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UnitKerjaProdiController implements the CRUD actions for UnitKerjaProdi model.
 */
class UnitKerjaProdiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UnitKerjaProdi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UnitKerjaProdiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionAjaxProdiSatker()
    {
        $results = [];
        $dataPost = $_POST['dataPost'];
        
        $prodiSatker = UnitKerjaProdi::find()->where([
            'unit_kerja_id' => $dataPost['unit_kerja_id'],
            'prodi_id'      => $dataPost['prodi_id']    ,
        ])->one();
        
        if (empty($prodiSatker)) {
            $prodiSatker = new UnitKerjaProdi();
            $prodiSatker->attributes = $dataPost;
            if ($prodiSatker->save()) {
                $results = [
                    'code'      => 200,
                    'message'   => 'data berhasil ditambah',
                ];
            }else {
                $error = \app\helpers\MyHelper::logError($prodiSatker);
                $results = [
                    'code'      => 500,
                    'message'   => $error,
                ];
            }
        }else {
            if($dataPost['checked'] == '0')
            {
                $prodiSatker->delete();
                $results = [
                    'code' => 200,
                    'message' => 'Bagian berhasil dihapus'
                ];
            }else {
                $error = \app\helpers\MyHelper::logError($prodiSatker);
                $results = [
                    'code'      => 500,
                    'message'   => $error,
                ];
            }
        }

        echo json_encode($results);
        exit;
    }


    /**
     * Displays a single UnitKerjaProdi model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UnitKerjaProdi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UnitKerjaProdi();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Data tersimpan");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing UnitKerjaProdi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Data tersimpan");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing UnitKerjaProdi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UnitKerjaProdi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UnitKerjaProdi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UnitKerjaProdi::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/unit-kerja-prodi/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerjaProdi */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="body">

    <?php $form = ActiveForm::begin([
    	'options' => [
            'id' => 'form_validation',
    	]
    ]); ?>



        <div class="form-group">
            <label class="control-label">Unit kerja</label>
            <?= $form->field($model, 'unit_kerja_id',['options' => ['tag' => false]])->textInput()->label(false) ?>

            
        </div>
                <div class="form-group">
            <label class="control-label">Prodi</label>
            <?= $form->field($model, 'prodi_id',['options' => ['tag' => false]])->textInput()->label(false) ?>

            
        </div>
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary waves-effect']) ?>
    
    <?php ActiveForm::end(); ?>

</div>

views/unit-kerja-prodi/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerjaProdiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="unit-kerja-prodi-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'unit_kerja_id') ?>

    <?= $form->field($model, 'prodi_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/unit-kerja-prodi/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UnitKerjaProdi */

$this->title = 'Create Unit Kerja Prodi';
$this->params['breadcrumbs'][] = ['label' => 'Unit Kerja Prodis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    	   </div>
        </div>
    </div>
</div>

views/unit-kerja-prodi/index.php
<?php

use app\helpers\MyHelper;
use app\models\Prodi;
use app\models\UnitKerja;
use app\models\UnitKerjaProdi;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UnitKerjaProdiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Unit Kerja Prodis';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">

                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <?php
                            $listUnitKerja = UnitKerja::find()->where(['jenis' => 'prodi'])->orderBy('singkatan ASC')->all();
                            foreach ($listUnitKerja as $unitKerja) {
                            ?>
                            <th><?= $unitKerja->singkatan ?></th>
                            <?php
                            }
                            ?>
                        </tr>
                    </thead>
                    <tbody>
                        
                    <?php
                        $listProdi = Prodi::find()->orderBy('nama_prodi ASC')->all();
                        foreach ($listProdi as $prodi) {
                        ?>
                        <tr>
                            <th><?= $prodi->nama_prodi; ?></th>

                            <?php
                            $x = 1;
                                foreach ($listUnitKerja as $unitKerja) {
                                    $m = UnitKerjaProdi::find()->where(['prodi_id' => $prodi->id, 'unit_kerja_id' => $unitKerja->id])->one();

                                    $checked = !empty($m) ? 'checked' : '';
                                ?>
                            <td style="text-align: center"><input type="checkbox" <?= $checked; ?> class="mycheck"
                                    data-prodi="<?= $prodi->id; ?>" data-unitkerja="<?= $unitKerja->id; ?>" value="1">
                            </td>
                            <?php
                            $x++;
                                }
                                ?>

                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>


<?php 


$script = ' 
$(".mycheck").change(function(){
    var unit_kerja      = $(this).data("unitkerja");
    var prodi           = $(this).data("prodi");
    var obj             = new Object;
    obj.unit_kerja_id   = unit_kerja;
    obj.prodi_id        = prodi;
    obj.checked         = $(this).prop("checked") ? "1" : "0";

    $.ajax({
        type    : "POST",
        url     : "'.Url::to(['unit-kerja-prodi/ajax-prodi-satker']).'",
        data    : {
            dataPost: obj
        },
        success : function(data){
            console.log(data)
        }
    });
});
';


$this->registerJs(
    $script,
    \yii\web\View::POS_READY
);

?>

views/unit-kerja-prodi/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerjaProdi */

$this->title = 'Update Unit Kerja Prodi: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Unit Kerja Prodis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
           </div>
        </div>
    </div>
</div>

views/unit-kerja-prodi/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerjaProdi */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Unit Kerja Prodis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="block-header">
    <h2><?= Html::encode($this->title) ?></h2>
</div>
<div class="row">
   <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>

            <div class="panel-body ">
        
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'unit_kerja_id',
            'prodi_id',
        ],
    ]) ?>

            </div>
        </div>

    </div>
</div>