controllers/UserController.php
<?php

namespace app\controllers;

use app\helpers\MyHelper;
use app\models\Auditor;
use app\models\AuthAssignment;
use app\models\UnitKerja;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\httpclient\Client;
use yii\web\ServerErrorHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    throw new \yii\web\ForbiddenHttpException('You are not allowed to access this page');
                },
                'only' => ['create', 'update', 'delete', 'index', 'view'],
                'rules' => [

                    [
                        'actions' => ['create', 'update', 'delete', 'index', 'view'],
                        'allow' => true,
                        'roles' => ['theCreator']
                    ],
                    [
                        'actions' => ['update', 'index', 'view'],
                        'allow' => true,
                        'roles' => ['admin']
                    ]
                ]
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (Yii::$app->request->post('hasEditable')) {

            $id = Yii::$app->request->post('editableKey');
            $model = User::findOne($id);

            $out = json_encode(['output' => '', 'message' => '']);

            $posted = current($_POST['User']);
            $post = ['User' => $posted];

            if ($model->load($post)) {
                if ($model->save()) {
                    $out = json_encode(['output' => '', 'message' => '']);
                } else {
                    $error = \app\helpers\MyHelper::logError($model);
                    $out = json_encode(['output' => '', 'message' => 'Oops, ' . $error]);
                }
            }
            echo $out;
            exit;
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionProfil()
    {
        $user = Yii::$app->user->identity;
        if ($user->access_role == 'auditor') {
            return $this->render('profil_auditor', [
                'user' => $this->findModel($user->id),
                'auditor' => Auditor::findOne($user->auditor_id),
            ]);
        } elseif ($user->access_role == 'auditee') {
            return $this->render('profil_auditee', [
                'user' => $this->findModel($user->id),
                'auditee' => UnitKerja::findOne($user->unit_kerja_id),
            ]);
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $user = new User(['scenario' => 'create']);


        if (!$user->load(Yii::$app->request->post())) {
            return $this->render('create', ['user' => $user]);
        }
        $pwd = $user->password;
        $user->setPassword($user->password);
        $user->generateAuthKey();
        // $user->item_name = $user->access_role;
        // $user->display_name = $user->first_name.' '.$user->last_name;


        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();

        if ($user->validate()) {
            try {


                if ($user->save()) {
                    $auth = Yii::$app->authManager;
                    $role = $auth->getRole($user->access_role);
                    $info = $auth->assign($role, $user->getId());

                    if (!$info)
                        throw new \Exception('There was some error while saving user role.');

                    Yii::$app->session->setFlash('success', 'Data successfully added');
                    $transaction->commit();
                } else {
                    $errors = MyHelper::logError($user);
                    Yii::$app->session->setFlash('error', Yii::t('app', $errors));
                }
            } catch (\Exception $e) {
                $transaction->rollBack();
                $errors = $e->getMessage();


                Yii::$app->session->setFlash('error', Yii::t('app', $errors));
            }
        } else
            return $this->render('create', ['user' => $user]);


        return $this->redirect('index');
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */


    public function actionAjaxFindUserSso()
    {
        $api_baseurl = Yii::$app->params['api_baseurl'];
        $client = new Client(['baseUrl' => $api_baseurl]);
        $client_token = Yii::$app->params['client_token'];
        $headers = ['x-access-token' => $client_token];

        $results = [
            'code' => 406,
            'message' => 'Bad Request'
        ];
        if (Yii::$app->request->isPost && !empty($_POST['dataPost']) && !empty($_POST['dataPost']['email'])) {

            $email = $_POST['dataPost']['email'];

            $response = $client->get('/sso/u/get', ['email' => $email], $headers)->send();
            $data_dosen = [];
            if ($response->isOk) {
                $hasil = $response->data['values'];
                $params = [
                    'uuid' => $hasil['uuid'],

                ];

                $resp = $client->get('/simpeg/dosen/profil', $params, $headers)->send();

                if ($resp->isOk) {
                    if (count($resp->data['values']) > 0) {
                        $data_dosen = $resp->data['values'][0];
                    }
                }
            }

            $results = [
                'code' => 200,
                'message' => 'Ok',
                'item' => $hasil,
                'password' => MyHelper::getRandomString(),
                'data_dosen' => $data_dosen
            ];
        }

        echo json_encode($results);
        exit;
    }

    public function actionUpdate($id)
    {
        $user = $this->findModel($id);

        $auth = Yii::$app->authManager;

        // get user role if he has one  
        if ($roles = $auth->getRolesByUser($id)) {
            // it's enough for us the get first assigned role name
            $role = array_keys($roles)[0];
        }

        // if user has role, set oldRole to that role name, else offer 'member' as sensitive default
        $oldRole = (isset($role)) ? $auth->getRole($role) : $auth->getRole('member');

        // set property item_name of User object to this role name, so we can use it in our form
        $user->access_role = $oldRole->name;

        if (!$user->load(Yii::$app->request->post())) {
            return $this->render('update', ['user' => $user, 'role' => $user->access_role]);
        }

        // only if user entered new password we want to hash and save it
        if ($user->password) {
            $user->setPassword($user->password);
        }

        // if admin is activating user manually we want to remove account activation token
        if ($user->status == User::STATUS_ACTIVE && $user->account_activation_token != null) {
            $user->removeAccountActivationToken();
        }

        $user->access_role = $user->access_role;

        if (!$user->save()) {
            return $this->render('update', ['user' => $user, 'role' => $user->access_role]);
        }

        // take new role from the form
        $newRole = $auth->getRole($user->access_role);
        // get user id too
        $userId = $user->getId();

        // we have to revoke the old role first and then assign the new one
        // this will happen if user actually had something to revoke
        if ($auth->revoke($oldRole, $userId)) {
            $info = $auth->assign($newRole, $userId);
        }

        // in case user didn't have role assigned to him, then just assign new one
        if (!isset($role)) {
            $info = $auth->assign($newRole, $userId);
        }

        if (!$info) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'There was some error while saving user role.'));
        }

        Yii::$app->session->setFlash('success', 'Data successfully updated');
        return $this->redirect(['index']);
    }

    public function actionUpdateAkun()
    {
        $id = Yii::$app->user->identity->id;
        $user = $this->findModel($id);

        $auth = Yii::$app->authManager;

        // get user role if he has one  
        if ($roles = $auth->getRolesByUser($id)) {
            // it's enough for us the get first assigned role name
            $role = array_keys($roles)[0];
        }

        // if user has role, set oldRole to that role name, else offer 'member' as sensitive default
        $oldRole = (isset($role)) ? $auth->getRole($role) : $auth->getRole('member');

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="body">

    <?php $form = ActiveForm::begin([
    	'options' => [
            'id' => 'form_validation',
    	]
    ]); ?>



        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Username</label>
        <div class="col-sm-9">
            <?= $form->field($model, 'username',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true])->label(false) ?>

            
            </div>
        </div>
                <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Uuid</label>
        <div class="col-sm-9">
            <?= $form->field($model, 'uuid',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true])->label(false) ?>

            
            </div>
        </div>
                <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Nama</label>
        <div class="col-sm-9">
            <?= $form->field($model, 'nama',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true])->label(false) ?>

            
            </div>
        </div>
                <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Email</label>
        <div class="col-sm-9">
            <?= $form->field($model, 'email',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true])->label(false) ?>

            
            </div>
        </div>
                <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Status</label>
        <div class="col-sm-9">
            <?= $form->field($model, 'status',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true])->label(false) ?>

            
            </div>
        </div>
                <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Access role</label>
        <div class="col-sm-9">
            <?= $form->field($model, 'access_role',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true])->label(false) ?>

            
            </div>
        </div>
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary waves-effect']) ?>
    
    <?php ActiveForm::end(); ?>

</div>

views/user/_form_profil.php
<?php

use app\models\Prodi;
use app\models\UnitKerja;
use app\rbac\models\AuthItem;
use kartik\password\PasswordInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use richardfan\widget\JSRegister;
use yii\jui\AutoComplete;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $user app\models\User */
/* @var $form yii\widgets\ActiveForm */

$list_roles = ArrayHelper::map(AuthItem::getRoles(), 'name', 'name');

?>
<?php foreach (AuthItem::getRoles() as $item_name) : ?>
    <?php $roles[$item_name->name] = $item_name->name ?>
<?php endforeach ?>
<?php foreach (UnitKerja::find()->all() as $item_name) : ?>
    <?php $unit_kerja[$item_name->id] = $item_name->nama ?>
<?php endforeach ?>


<div class="body">

    <?php $form = ActiveForm::begin(['id' => 'form-user']); ?>
    <?= $form->errorSummary($user, ['header' => '<div class="alert alert-danger">', 'footer' => '</div>']); ?>

    <?= $form->field($user, 'nama')->input('nama', ['placeholder' => Yii::t('app', 'Enter e-mail')]) ?>

    <?= $form->field($user, 'username')->textInput(
        ['placeholder' => Yii::t('app', 'Create username'), 'autofocus' => true]
    ) ?>
    
    <?= $form->field($user, 'email')->input('email', ['placeholder' => Yii::t('app', 'Enter e-mail')]) ?>

    <?php if ($user->scenario === 'create') : ?>

        <?= $form->field($user, 'password')->widget(
            PasswordInput::classname(),
            ['options' => ['placeholder' => Yii::t('app', 'Create password')]]
        ) ?>

    <?php else : ?>

        <?= $form->field($user, 'password')->widget(
            PasswordInput::classname(),
            ['options' => ['placeholder' => Yii::t('app', 'Change password ( if you want )')]]
        ) ?>

    <?php endif ?>

    <div class="form-group">
        <?= Html::submitButton($user->isNewRecord ? Yii::t('app', 'Create')
            : Yii::t('app', 'Update'), ['class' => $user->isNewRecord
            ? 'btn btn-success' : 'btn btn-primary']) ?>

        <?= Html::a(Yii::t('app', 'Cancel'), ['user/profil'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<?php JSRegister::begin(); ?>
<script>
    $(document).on("click", "#btn-add-role", function(e) {
        e.preventDefault()

        $("#exampleModal").modal("show");
    })

    $(document).on('change', '#dosen', function(e) {
        e.preventDefault();
        $("#nim").val($(this).val());
    });

    $(document).on("click", "#btn-save", function(e) {
        e.preventDefault()

        var obj = new Object;
        obj.user_id = $("#user_id").val();
        obj.item_name = $("#item_name").val();

        $.ajax({
            type: 'POST',
            url: "/user/ajax-add-role",
            data: {
                dataPost: obj
            },
            async: true,
            error: function(e) {
                Swal.hideLoading();

            },
            beforeSend: function() {
                Swal.showLoading();
            },
            success: function(data) {
                var hasil = $.parseJSON(data)
                if (hasil.code == 200) {

                    Swal.fire({
                        title: 'Yeay!',
                        icon: 'success',
                        text: hasil.message
                    }).then((result) => {
                        if (result.value) {
                            location.reload();
                        }
                    });
                } else {
                    Swal.fire({
                        title: 'Oops!',
                        icon: 'error',
                        text: hasil.message
                    }).then((result) => {
                        if (result.value) {
                            location.reload();
                        }
                    });
                }
            }
        })
    })

    $(document).on("click", ".btn-remove-role", function(e) {
        e.preventDefault()

        var obj = new Object;
        obj.user_id = $(this).data("user");
        obj.item_name = $(this).data("item");

        $.ajax({
            type: 'POST',
            url: "/user/ajax-delete-role",
            data: {
                dataPost: obj
            },
            async: true,
            error: function(e) {
                Swal.hideLoading();
            },
            beforeSend: function() {
                Swal.showLoading();
            },
            success: function(data) {
                var hasil = $.parseJSON(data)
                if (hasil.code == 200) {

                    Swal.fire({
                        title: 'Yeay!',
                        icon: 'success',
                        text: hasil.message
                    }).then((result) => {
                        if (result.value) {
                            location.reload();
                        }
                    });
                } else {
                    Swal.fire({
                        title: 'Oops!',
                        icon: 'error',
                        text: hasil.message
                    }).then((result) => {
                        if (result.value) {
                            location.reload();
                        }
                    });
                }
            }
        })
    })
</script>
<?php JSRegister::end(); ?>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'uuid') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'otp') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'access_role') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    	   </div>
        </div>
    </div>
</div>

views/user/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
<div class="x_content">

    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php
    $gridColumns = [
    [
        'class'=>'kartik\grid\SerialColumn',
        'contentOptions'=>['class'=>'kartik-sheet-style'],
        'width'=>'36px',
        'pageSummary'=>'Total',
        'pageSummaryOptions' => ['colspan' => 6],
        'header'=>'',
        'headerOptions'=>['class'=>'kartik-sheet-style']
    ],
            'id',
            'username',
            'uuid',
            'nama',
            'email:email',
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
            //'otp',
            //'status',
            //'access_role',
            //'created_at',
            //'updated_at',
    ['class' => 'yii\grid\ActionColumn']
];?>    
<?= GridView::widget([
        'pager' => [
            'options'=>['class'=>'pagination'],  
            'activePageCssClass' => 'active paginate_button page-item',
            'disabledPageCssClass' => 'disabled paginate_button',
            'prevPageLabel' => 'Previous',   
            'nextPageLabel' => 'Next',  
            'firstPageLabel'=>'First',  
            'lastPageLabel'=>'Last',    
            'nextPageCssClass'=>'paginate_button next page-item',   
            'prevPageCssClass'=>'paginate_button previous page-item',  
            'firstPageCssClass'=>'first paginate_button page-item',    
            'lastPageCssClass'=>'last paginate_button page-item',   
            'maxButtonCount'=>10,    
            'linkOptions' => [
                'class' => 'page-link'
            ]
        ],      
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'responsiveWrap' => false,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'], 
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'containerOptions' => ['style'=>'overflow: auto'], 
        'beforeHeader'=>[
            [
                'columns'=>[
                    ['content'=> $this->title, 'options'=>['colspan'=>14, 'class'=>'text-center warning']], //cuma satu 
                ], 
                'options'=>['class'=>'skip-export'] 
            ]
        ],
        'exportConfig' => [
              GridView::PDF => ['label' => 'Save as PDF'],
              GridView::EXCEL => ['label' => 'Save as EXCEL'], //untuk menghidupkan button export ke Excell
              GridView::HTML => ['label' => 'Save as HTML'], //untuk menghidupkan button export ke HTML
              GridView::CSV => ['label' => 'Save as CSV'], //untuk menghidupkan button export ke CVS
          ],
          
        'toolbar' =>  [
            '{export}', 

           '{toggleData}' //uncoment untuk menghidupkan button menampilkan semua data..
        ],
        'toggleDataContainer' => ['class' => 'btn-group mr-2'],
    // set export properties
        'export' => [
            'fontAwesome' => true
        ],
        'pjax' => true,
        'pjaxSettings' =>[
            'neverTimeout'=>true,
            'options'=>[
                'id'=>'pjax-container',
            ]
        ],  
        'id' => 'my-grid',
        'bordered' => true,
        'striped' => true,
        // 'condensed' => false,
        // 'responsive' => false,
        'hover' => true,
        // 'floatHeader' => true,
        // 'showPageSummary' => true, //true untuk menjumlahkan nilai di suatu kolom, kebetulan pada contoh tidak ada angka.
        'panel' => [
            'type' => GridView::TYPE_PRIMARY
        ],
    ]); ?>

</div>
        </div>
    </div>

</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
            </div>
        </div>
    </div>
</div>

views/user/update_profil.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user app\models\User */

$this->title = 'Update Profile Akun: ' . $user->nama;
$this->params['breadcrumbs'][] = ['label' => 'Profil', 'url' => ['user/profil']];
$this->params['breadcrumbs'][] = 'Update Profil Akun';
?>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">
                <?= $this->render('_form_profil', [
                    'user' => $user,
                ]) ?>
            </div>
        </div>
    </div>
</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="block-header">
    <h2><?= Html::encode($this->title) ?></h2>
</div>
<div class="row">
   <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>

            <div class="panel-body ">
        
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'uuid',
            'nama',
            'email:email',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'otp',
            'status',
            'access_role',
            'created_at',
            'updated_at',
        ],
    ]) ?>

            </div>
        </div>

    </div>
</div>