models/JenjangMap.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "jenjang_map".
 *
 * @property int $id
 * @property int|null $unit_kerja_id
 * @property int|null $jenjang_id
 *
 * @property Jenjang $jenjang
 * @property UnitKerja $unitKerja
 */
class JenjangMap extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'jenjang_map';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['unit_kerja_id', 'jenjang_id'], 'integer'],
            [['jenjang_id'], 'exist', 'skipOnError' => true, 'targetClass' => Jenjang::class, 'targetAttribute' => ['jenjang_id' => 'id']],
            [['unit_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => UnitKerja::class, 'targetAttribute' => ['unit_kerja_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unit_kerja_id' => 'Unit Kerja ID',
            'jenjang_id' => 'Jenjang ID',
        ];
    }

    /**
     * Gets query for [[Jenjang]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJenjang()
    {
        return $this->hasOne(Jenjang::class, ['id' => 'jenjang_id']);
    }

    /**
     * Gets query for [[UnitKerja]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUnitKerja()
    {
        return $this->hasOne(UnitKerja::class, ['id' => 'unit_kerja_id']);
    }
}

controllers/JenjangMapController.php
<?php

namespace app\controllers;

use Yii;
use app\models\JenjangMap;
use app\models\JenjangMapSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * JenjangMapController implements the CRUD actions for JenjangMap model.
 */
class JenjangMapController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all JenjangMap models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JenjangMapSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single JenjangMap model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new JenjangMap model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new JenjangMap();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Data tersimpan");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionAjaxJenjangMap()
    {
        $results = [];
        $dataPost = $_POST['dataPost'];
        
        $jenjangMap = JenjangMap::find()->where([
            'unit_kerja_id' => $dataPost['unit_kerja_id']
        ])->one();
        
        #check data
        // echo '<pre>';print_r(!empty($jenjangMap));die;
        if (!empty($jenjangMap)) {
            $jenjangMap->attributes = $dataPost;
            if($jenjangMap->save())
            {
                $results = [
                    'code' => 200,
                    'message' => 'Jenjang Prodi Berhasil di Update'
                ];
            }
        }else {
            $jenjangMap = new JenjangMap();
            $jenjangMap->attributes = $dataPost;
            if($jenjangMap->save())
            {
                $results = [
                    'code' => 200,
                    'message' => 'App Role Added'
                ];
            }

            else
            {
                $error = \app\helpers\MyHelper::logError($jenjangMap);
                $results = [
                    'code' => 500,
                    'message' => $error
                ];
            }
        }

        echo json_encode($results);
        
        exit;
    }

    /**
     * Updates an existing JenjangMap model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Data tersimpan");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing JenjangMap model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the JenjangMap model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return JenjangMap the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = JenjangMap::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/jenjang-map/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\JenjangMap */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="body">

    <?php $form = ActiveForm::begin([
    	'options' => [
            'id' => 'form_validation',
    	]
    ]); ?>



        <div class="form-group">
            <label class="control-label">Unit kerja</label>
            <?= $form->field($model, 'unit_kerja_id',['options' => ['tag' => false]])->textInput()->label(false) ?>

            
        </div>
                <div class="form-group">
            <label class="control-label">Jenjang</label>
            <?= $form->field($model, 'jenjang_id',['options' => ['tag' => false]])->textInput()->label(false) ?>

            
        </div>
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary waves-effect']) ?>
    
    <?php ActiveForm::end(); ?>

</div>

views/jenjang-map/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\JenjangMapSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="jenjang-map-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'unit_kerja_id') ?>

    <?= $form->field($model, 'jenjang_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/jenjang-map/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\JenjangMap */

$this->title = 'Create Jenjang Map';
$this->params['breadcrumbs'][] = ['label' => 'Jenjang Maps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    	   </div>
        </div>
    </div>
</div>

views/jenjang-map/index.php
<?php

use app\models\Jenjang;
use app\models\JenjangMap;
use app\models\UnitKerja;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\JenjangMapSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Jenjang Maps';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">

                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <?php
                            $listJenjang = Jenjang::find()->orderBy('urutan ASC')->all();
                            foreach ($listJenjang as $jenjang) {
                            ?>
                                <th><?= $jenjang->nama; ?></th>
                            <?php
                            }
                            ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $listUnit = UnitKerja::find()->orderBy('nama ASC')->where(['not', ['jenis' => 'satker']])->all();
                        foreach ($listUnit as $unit) {
                        ?>
                            <tr>
                                <th><?= $unit->nama; ?></th>

                                <?php
                                foreach ($listJenjang as $jenjang) {
                                    $m = JenjangMap::find()->where(['unit_kerja_id' => $unit->id, 'jenjang_id' => $jenjang->id])->one();

                                    $checked = !empty($m) ? 'checked' : '';
                                ?>
                                    <td><input name="<?= $unit->id ?>" type="radio" <?= $checked; ?> class="mycheck" data-unit="<?= $unit->id; ?>" data-jenjang="<?= $jenjang->id; ?>" value="1">
                                    </td>
                                <?php
                                }
                                ?>

                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>


<?php


$script = ' 
$(".mycheck").change(function(){
    var unit            = $(this).data("unit");
    var jenjang         = $(this).data("jenjang");
    var obj             = new Object;
    obj.unit_kerja_id   = unit;
    obj.jenjang_id      = jenjang;
    obj.checked         = $(this).prop("checked") ? "1" : "0";

    $.ajax({
        type : "POST",
        url : "' . Url::to(['jenjang-map/ajax-jenjang-map']) . '",
        data : {
            dataPost: obj
        },
        success : function(data){
            console.log(data)
        }
    });
});
';


$this->registerJs(
    $script,
    \yii\web\View::POS_READY
);

?>

views/jenjang-map/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\JenjangMap */

$this->title = 'Update Jenjang Map: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Jenjang Maps', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h3><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="x_content">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
           </div>
        </div>
    </div>
</div>

views/jenjang-map/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\JenjangMap */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Jenjang Maps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="block-header">
    <h2><?= Html::encode($this->title) ?></h2>
</div>
<div class="row">
   <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>

            <div class="panel-body ">
        
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'unit_kerja_id',
            'jenjang_id',
        ],
    ]) ?>

            </div>
        </div>

    </div>
</div>